### PR TITLE
Fix layers with style sub attributes for display

### PR DESCRIPTION
**Pull request by dredenba**
fix bug where display attribute and display data in style attribute conflict and result in incorrect behavior

### CODE REVIEW

**Comment by wader** [comment]
Very nice with test also!

**Comment by dredenba** [comment]
pushed up a new commit with the style changes. i think I got it all but let me know if i missed something

**Comment by wader** [comment]
Merged! thanks :+1:

**Comment by wader** [comment]
Just of curiosity, what are you using inkmake for?

**Comment by dredenba** [comment]
I am using it as part of my workflow for generating assets. I have shifted most of my graphics work to vector based stuff in Inkscape because I find the need to generate a number of different sizes and variations across all the different platforms I work on and I like the smaller file sizes. Inkmake allows me to streamline some of my exporting that I was doing by hand within Inkscape. In addition to saving me the time of a few clicks it also allows me to make the generation of the assets more easily repeatable. I also share the svg and inkmake files with my team so that they can generate the assets the same way by just running the inkmake file so they don't have to understand as much about using Inkscape.

**Comment by wader** [comment]
Ok! sounds more or less like the itch i had also :)

I just pushed an update to gemify inkmake, hope you like it

**Pull request merged**
